- name: basic information
  hosts: all
  gather_facts: true
  become: true
  #
  vars:
    cluster_admin: ubuntu
    admin_user:    ubuntu
    my_host:   gitlab
    fqdn:      "{{ my_host }}.labo.local"
    my_data:   /gitlab
    dst_dir:   /gitlab/config/ssl
    disk_sdc:  "{{ my_data }}"
    public_ip_addr: 192.168.1.222    
    public_ip_dns:  192.168.1.241
    ca_ip:          192.168.1.220
    disk1: "/dev/vdb"
    disk2: "/dev/vdc"
    
  #   
  roles:
    - base_linux
    - docker
    - vdisks
    - download_certs        

  # 
  tasks:
  - name: Re-Start dockerd
    systemd:
      name: docker
      state: restarted
      daemon_reload: yes
      enabled: yes
    
  - name: copy docker-compose.yml
    template:
      src: docker-compose.yml
      dest: "{{ my_data }}"

  - name: Start Gitlab container
    shell: |
      docker-compose up -d
    args:
      chdir: "{{ my_data }}"
