- name: basic information
  hosts: all
  gather_facts: true
  become: true
  #
  vars:
    my_host: gitlab
    my_domain: "{{ my_host }}.labo.local"
    my_data: /gitlab
    disk_sdc: "{{ my_data }}"    
  #   
  roles:
    - docker
    - vdisks
  # 
  tasks:
  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

      
  - name: mkdir {{ my_data }}/config/ssl
    file:
      path: "{{ my_data }}/config/ssl"
      state: directory
      owner: root
      group: root
      mode: '0775'      

  - name: Create v3.ext
    template:
      src: v3.ext.j2
      dest: "{{ my_data }}/config/ssl/v3.ext"
      
  - shell: |
      openssl genrsa -out ca.key 4096
      openssl req -x509 -new -nodes -sha512 -days 3650 \
         -subj "/C=JP/ST=Tokyo/L=Tokyo/O=homelab/OU=homelab/CN={{ my_domain }}" \
         -key ca.key \
         -out ca.crt
      openssl genrsa -out "{{ my_domain }}.key" 4096
      touch /root/.rnd
      openssl req -sha512 -new \
         -subj "/C=JP/ST=Tokyo/L=Tokyo/O=homelab/OU=homelab/CN={{ my_domain }}" \
         -key "{{ my_domain }}.key" \
         -out "{{ my_domain }}.csr"
      openssl x509 -req -sha512 -days 3650 \
        -extfile v3.ext \
        -CA ca.crt -CAkey ca.key -CAcreateserial \
        -in "{{ my_domain }}.csr" \
        -out "{{ my_domain }}.crt"
    args:
      chdir: "{{ my_data }}/config/ssl"
  #
  - name: Re-Start dockerd
    systemd:
      name: docker
      state: restarted
      daemon_reload: yes
      enabled: yes
    
  - name: copy docker-compose.yml
    template:
      src: docker-compose.yml
      dest: "{{ my_data }}"

  - name: Start Gitlab container
    shell: |
      docker-compose up -d
    args:
      chdir: "{{ my_data }}"
